version: 0.0
os: linux
files:
  - source: target/Calculator-1.0-SNAPSHOT.jar
    destination: /opt/tomcat/webapps

hooks:
  BeforeInstall:
    - location: /opt/tomcat/bin/shutdown.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: /opt/tomcat/bin/startup.sh
      timeout: 300
      runas: ubuntu
