version: 0.0
os: linux
files:
  - source: target/Calculator-1.0-SNAPSHOT.jar
    destination: /opt/tomcat/webapps

hooks:
  BeforeInstall:
    - location: /home/ubuntu/stop.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location:/home/ubuntu/startsh
      timeout: 300
      runas: ubuntu
