version: 0.0
os: linux
files:
  - source: target/calc.jar
    destination: /opt/tomcat/webapps

hooks:
  BeforeInstall:
    - location: /opt/tomcat/webapps/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: /opt/tomcat/webapps/scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /opt/tomcat/webapps/scripts/verify_service.sh
      timeout: 300
      runas: ubuntu
