version: 0.0
os: linux
files:
  - source: target/Calculator-1.0-SNAPSHOT.jar
    destination: /opt/tomcat/webapps

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
