version: 0.0
os: linux
files:
  - source: target/.war
    destination: /usr/local/tomcat/webapps/ROOT.war

hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/verify_service.sh
      timeout: 300
      runas: root
